logging:
  level:
    jdbc:
      sqlonly: info
      resultsettable: info
      sqltiming: fatal
      audit: fatal
      resultset: fatal
      connection: fatal
    org:
      springframework:
        orm:
          jpa: debug
      hibernate:
        stat: debug
        hql: debug
        cache: info
        jdbc: debug
#    com:
#      hazelcast: debug
spring:
  jpa:
    open-in-view: false
    properties:
      javax.persistence.sharedCache.mode: ENABLE_SELECTIVE
      hibernate:
        generate_statistics: true

        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 10
          fetch_size: 10
          batch_versioned_data: true

        cache:
          use_second_level_cache: true
          use_minimal_puts: true
#          region.factory_class: com.hazelcast.hibernate.HazelcastCacheRegionFactory
          region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
          use_query_cache: true
          use_structured_entries: true
#          hazelcast:
#            use_native_client: false
#            native_client_hosts: 127.0.0.1
#            native_client_group: hibernate
#            native_client_password: password

